spring:
  application:
    name: Attendance-API
  datasource:
    url: jdbc:mysql://localhost:3306/attendance_project?createDatabaseIfNotExist=true
    username: root
    password: Mohamed1212#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration : 28800 #8h
  refreshTokenExpiration : 604800 #7d