spring:
  application:
    name: Attendance-API
  datasource:
    url: ${URL_DATABASE}
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration : 28800 #8h
  refreshTokenExpiration : 604800 #7d